name: CI con Matriz Python

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # Permite activarlo manualmente desde la web

jobs:
  test-versions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v3

    - name: Configurar Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Mostrar versión
      run: python --version

    - name: Instalar dependencias (Simulado)
      run: |
        python -m pip install --upgrade pip
        # Si tuvieras librerías, aquí harías pip install -r requirements.txt

    - name: Ejecutar Test de Seguridad (Ejercicio 4)
      # Ajusta el nombre del archivo si le pusiste otro en el Ejercicio 4
      run: |
        if [ -f "seguridad/scanner_puertos.py" ]; then
          python seguridad/scanner_puertos.py
        elif [ -f "seguridad/audit_security.py" ]; then
          python seguridad/audit_security.py
        elif [ -f "seguridad/docker_security_scan.py" ]; then
          python seguridad/docker_security_scan.py
        else
          echo "No se encontró script de seguridad, saltando test..."
        fi
